server:
  port: 8080

logging:
  level:
    com.real.estate.price: INFO

spring:
  r2dbc:
    url: r2dbc:h2:mem:///estate
    username: admin
    password: password

external-api:
  number-of-retries: 3
  cron: 0 0 21 * * *
  offer-service-host: http://localhost:8081
