server:
  port: 8080

logging:
  level:
    com.real.estate.price: INFO

spring:
  r2dbc:
    url: r2dbc:h2:mem:///estate
    username: admin
    password: password
  h2:
    console:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: username@gmail.com
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    receiver: receiver@gmail.com

external-api:
  number-of-retries: 3
  cron: 0 0 21 * * *

